### ISSUE TITLE
has $VAULT_ADDR but Client sent an HTTP request to an HTTPS server

### ISSUE THREAD

**Issue by rllzyy** [openlab-red/hashicorp-vault-for-openshift#20]
Can anyone help for this? thx a lot!  based on OCP 4.3
Steps:
1.oc new-project hashicorp
2.git clone https://github.com/hashicorp/consul-helm.git /tmp/consul-helm
3.helm install --name consul /tmp/consul-helm
4.oc -n hashicorp patch sts consul-consul-server --type json --patch="[
  {"op": "remove", "path": "/spec/template/spec/securityContext"}
]"
5.oc -n hashicorp create route reencrypt consul --port=8500 --service=consul-consul-server
6.git clone https://github.com/openlab-red/hashicorp-vault-for-openshift.git
7.cd hashicorp-vault-for-openshift
8.oc apply -f ./vault/ha/install/     
     _(vault-0 vault-1 vault-2 are running but READY are 0/1)
     (logs as following ==> Vault server configuration:
             Api Address: http://10.130.2.83:8200
                     Cgo: disabled
            Cluster Address: https://10.130.2.83:8201
              Listener 1: tcp (addr: "[::]:8200", cluster address: "[::]:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "enabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
           Recovery Mode: false
                 Storage: consul (HA available)
                 Version: Vault v1.3.2
        ==> Vault server started! Log data will stream in below:
2020-04-14T09:49:01.939Z [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=
2020-04-14T09:49:01.940Z [WARN]  storage.consul: appending trailing forward slash to path)_

9.oc rsh vault-0
10.echo $VAULT_ADDR  (show http://127.0.0.1:8200)
11.vault operator init -key-shares=1 -key-threshold=1

Results:
Error checking seal status: Error making API request.
URL: GET http://127.0.0.1:8200/v1/sys/seal-status
Code: 400. Raw Message:
Client sent an HTTP request to an HTTPS server.

**Comment by eye0fra** [comment]
Hi @rllzyy, 

the default $VAULT_ADDR variable should be https://127.0.0.1:8200, https endpoint.

**Comment by rllzyy** [comment]
@eye0fra thx I just modify 015-StatefulSet-vault.yaml
- name: VAULT_ADDR
   value: **https://127.0.0.1:8200**
and I need to add the following var for vault operator unseal $KEYS. or use --tls-skip-verify
- name: VAULT_SKIP_VERIFY
          value: "true"
so I do the following
curl https://vault-hashicorp.apps.xxxxxxx.com/v1/sys/init --insecure
it works temprary!

But I want to enable verify, so I export VAULT_SKIP_VERIFY=false, and I found it use cert with
oc rsh vault-0 
cat vault/config/extraconfig-from-values.hcl, it shows

_listener "tcp" {
  address = "[::]:8200"
  cluster_address = "[::]:8201"
  tls_cert_file = "/var/run/secrets/kubernetes.io/certs/tls.crt"
  tls_key_file = "/var/run/secrets/kubernetes.io/certs/tls.key"
}_

so I just use:
vault status -ca-cert=/var/run/secrets/kubernetes.io/certs/tls.crt 
but failed with 
"Error checking seal status: Get https://127.0.0.1:8200/v1/sys/seal-status: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs"

should I modify the address with **address = "127.0.0.1:8200"**?
could you please help me for how can I use the tls.cet? thx a lot

**Comment by eye0fra** [comment]
The TLS certificate specified in the vault config is used for internal communication in the cluster (vault service).

So if you want to launch the _vault status_ inside the pod.

```
export VAULT_ADDR=https://vault.hashicorp.svc:8200
export VAULT_CAPATH=/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt

vault status
```

From the external communication (like the curl command) you need to use the CA used for your OpenShift Cluster. You can retrieve it from the pod:

```
oc exec vault-0 -- cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt > ca.crt
curl --cacert ca.crt  https://vault-hashicorp.apps.xxxxxxx.com/v1/sys/seal-status
```

**Comment by rllzyy** [comment]
@eye0fra thx a lot! it works!  👍  I think it can be closed!
