### ISSUE TITLE
Mutation webhook failing

### ISSUE THREAD

**Issue by JoshStead** [openlab-red/hashicorp-vault-for-openshift#22]
Hi, I'm trying to deploy the vault injector sidecar on it own so it can communicate with an external vault instance. I am running on OCP 4.3.10

With the injector deployed I am attempting to run a sample app but the pod does not come up and has the below error:

Internal error occurred: failed calling webhook "vault.hashicorp.com": Post https://vault-agent-injector-svc.hashicorp.svc:443/mutate?timeout=5s: context deadline exceeded

Any Ideas?, looking online its previously happened when firewall ported needed to be opened

**Comment by JoshStead** [comment]
also I have modified 013-Deployment-vault-injector.yaml to change AGENT_INJECT_VAULT_ADDR to the vault IP address and AGENT_INJECT_TLS_AUTO_HOSTS as the $(namespace) was not being populated

**Comment by eye0fra** [comment]
Hi @JoshStead  can you check the replication controllers status of your application? 
You should see an error with more details about the context deadline exceeded issue.
It is interesting that $NAMESPACE variable is not populated.

If you curl -k https://vault-agent-injector-svc.hashicorp.svc:443/mutate from one of the apiserver on openshift-apiserver namespace are you able to reach it ?

**Comment by eye0fra** [comment]
The Networkpolicy in the project was wrong can you re-apply again?
https://github.com/openlab-red/hashicorp-vault-for-openshift/pull/23

**Comment by JoshStead** [comment]
Hi @eye0fra 

Sorry for the late response, I will give this a try tomorrow and get back to you. Been having some other vault issues. 

Thanks

**Comment by JoshStead** [comment]
Hi @eye0fra 

That's fixed that issue for me now :) - I am able to create a new deployment now and the pod will run without the error I was seeing before. I'm not able to test the injector functionality just yet (still working through some vault config).

The injector environment vars is still showing as $(namespace) in AGENT_INJECT_TLS_AUTO_HOSTS - any ideas?

<img width="1000" alt="Screenshot 2020-04-23 at 10 06 44" src="https://user-images.githubusercontent.com/53786642/80081043-55190a80-854a-11ea-8f4c-4f0f2bb6ba21.png">

**Comment by eye0fra** [comment]
Awesome! If you check inside the pod with `env` command you still see the $(NAMESPACE)?

**Comment by JoshStead** [comment]
Ahh :) - It has the correct project name 

<img width="1088" alt="Screenshot 2020-04-23 at 13 30 17" src="https://user-images.githubusercontent.com/53786642/80099723-d7afc300-8566-11ea-877d-94b85155c4d3.png">


Happy for you to close this issue - thanks for your help - I may come back here if I get any issues with the injector

**Comment by eye0fra** [comment]
👍🙃 welcome!
