### ISSUE TITLE
Error updating MutatingWebhookConfiguration

### ISSUE THREAD

**Issue by panderm** [openlab-red/hashicorp-vault-for-openshift#28]
mutatingwebhookconfigurations.admissionregistration.k8s.io "vault-agent-injector-cfg" is forbidden: User "system:serviceaccount:hashicorp:vault-injector" cannot patch resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope 

To fix this issue, must add patch privilege in file /vault/injector/install/010-ClusterRole-vault-injector.yaml :
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-injector-clusterrole
  labels:
    app.kubernetes.io/name: vault-injector
    app.kubernetes.io/instance: vault
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: 
    - "get"
    - "list"
    - **"patch"**
    - "watch"

**Comment by JoshStead** [comment]
I think this file has recently changed, I have a clone from a few weeks back and it contains the patch. Looking back this was removed in PR 26. I am having the same issue as the author.

**Comment by eye0fra** [comment]
Yeap you right, can you make a PR to fix it? Thanks a lot
