### ISSUE TITLE
CHART YAML

### ISSUE THREAD

**Issue by attmesh** [openlab-red/hashicorp-vault-for-openshift#40]
Hello, 
When I run the helm install standalone . -f override-standalone.yaml 
 
 It gives Chart.yaml is missing

**Comment by attmesh** [comment]
The issue was I was outside the folder. 
But again it's giving error after I solved the first one
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Route" in version "route.openshift.io/v1"

**Comment by radudd** [comment]
Thanks @attmesh for reporting the issue. The OpenShift Route API changed and we didn't synced yet the forked repo from the upstream. We'll fix that.

**Comment by attmesh** [comment]
@radudd Sure. Thanks for the update. Is it synced yet?

**Comment by vieenodp** [comment]
I am getting this error on Openshift 4.9  mkdir: can't create directory '/consul/extra-config: Permission denied , Is this repo still valid for 4.9 ?

**Comment by eye0fra** [comment]
We recently update the instruction using the recommended storage raft.
