### ISSUE TITLE
deploy failed on okd 3.11

### ISSUE THREAD

**Issue by vanloswang** [openlab-red/hashicorp-vault-for-openshift#6]
The vault container failed to run with following error logs:
```
chown: /vault/file: Operation not permitted
chown: /vault/file: Operation not permitted
```

**Comment by eye0fra** [comment]
Have you given the permission to the service account ?

`oc adm policy add-scc-to-user privileged -z default`

**Comment by vanloswang** [comment]
@eye0fra Yes, I follow the commands in readme, and check it by following command:
```
oc get scc privileged -o yaml | grep system:serviceaccount:hashicorp-vault:default
```
In https://github.com/raffaelespazzoli/credscontroller/issues/8, raffaelespazzoli  give me some suggestions.
