### ISSUE TITLE
Update Vault Charts from upstream?

### ISSUE THREAD

**Issue by boldandbusted** [openlab-red/hashicorp-vault-for-openshift#74]
Howdy. The project had forked Vault helm charts 3 years ago, and sadly hasn't updated them since then. A lot has changed in Vault, the Vault Helm Charts and related artifacts. Can you please update the fork with the latest updates? Or integrate your changes into the upstream chart? Thanks! :)

Ref: "This includes for now only the possibility to create OpenShift passthrough routes, but we [forked these official charts](http://github.com/radudd/vault-helm) and added the possibility to use reencrypt routes and to rely on OpenShift internal CA for signing Vault"

**Comment by eye0fra** [comment]
Hi @boldandbusted ,

Take a look at this [article](https://github.com/openlab-red/hashicorp-vault-for-openshift/blob/master/articles/Secure%20Cloud%20Native%20App.md) and a related [ArgoCD sample](https://github.com/openlab-red/hashicorp-vault-for-openshift/tree/master/deploy) for more information on how to use the official helm chart.

Hashicorp Vault now supports customizable TLS termination for the [route](https://github.com/hashicorp/vault-helm/blob/main/values.yaml#L459), making the fork unnecessary.
